# Generated by Django 3.2.7 on 2023-01-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.AlterField(
            model_name='booking',
            name='From',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='To',
            field=models.DateTimeField(),
        ),
    ]
