# Generated by Django 3.2.7 on 2023-01-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0003_auto_20230109_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='From',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='To',
            field=models.DateTimeField(),
        ),
    ]
