# Generated by Django 3.2.7 on 2023-01-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0006_parkingspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=50)),
            ],
        ),
    ]
