# Generated by Django 3.2.7 on 2023-01-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('time_of_entry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
