# Generated by Django 3.2.7 on 2023-02-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
    ]
