# Generated by Django 3.2.7 on 2023-02-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_alter_vehiclecategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('bicycle', 'Bicycle'), ('commercial', 'Commercial Vehicles')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='parkingcharge',
            name='vehicle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.vehicle_category'),
        ),
        migrations.DeleteModel(
            name='VehicleCategory',
        ),
    ]
