# Generated by Django 3.2.7 on 2023-02-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0005_auto_20230220_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('yearly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.vehicle_category')),
            ],
        ),
        migrations.DeleteModel(
            name='ParkingCharge',
        ),
    ]
