# Generated by Django 3.2.7 on 2023-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_auto_20230220_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_category',
            name='name',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('bicycle', 'Bicycle'), ('commercial', 'Commercial Vehicles')], max_length=50),
        ),
    ]
