# Generated by Django 3.2.7 on 2023-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0008_auto_20230220_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('bicycle', 'Bicycle'), ('commercial', 'Commercial Vehicles')], max_length=50),
        ),
        migrations.AlterField(
            model_name='parking_charge',
            name='vehicle_category',
            field=models.CharField(max_length=20),
        ),
    ]
