# Generated by Django 3.2.7 on 2023-02-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0010_auto_20230220_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingCharge',
        ),
        migrations.DeleteModel(
            name='VehicleCategory',
        ),
    ]
