# Generated by Django 3.2.7 on 2023-02-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0013_parkingsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('bicycle', 'Bicycle'), ('commercial', 'Commercial Vehicles')], max_length=50, unique=True)),
                ('slot_number', models.CharField(max_length=10)),
                ('floor_number', models.IntegerField()),
                ('number_of_spots', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
                ('availability', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='vacant', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='parkingcharge',
            name='vehicle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.vehicle_category'),
        ),
        migrations.AlterField(
            model_name='parkingsearch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.vehicle_category'),
        ),
        migrations.DeleteModel(
            name='VehicleCategory',
        ),
    ]
