# Generated by Django 3.2.7 on 2023-02-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0016_auto_20230222_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingcharge',
            name='vehicle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.vehicle_category', unique=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('parking_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.parkingcharge')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.generate_spot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.vehicle_category')),
            ],
        ),
    ]
