# Generated by Django 3.2.7 on 2023-02-23 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0017_auto_20230222_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('vehicle_number', models.CharField(max_length=255)),
                ('parking_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.parkingcharge')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.generate_spot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.vehicle_category')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
