# Generated by Django 3.2.7 on 2023-02-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0018_auto_20230223_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generate_spot',
            name='category',
        ),
        migrations.RemoveField(
            model_name='parkingcharge',
            name='vehicle_category',
        ),
        migrations.RemoveField(
            model_name='parkingsearch',
            name='category',
        ),
        migrations.DeleteModel(
            name='BookingRecord',
        ),
        migrations.DeleteModel(
            name='Generate_Spot',
        ),
        migrations.DeleteModel(
            name='ParkingCharge',
        ),
        migrations.DeleteModel(
            name='ParkingSearch',
        ),
        migrations.DeleteModel(
            name='Vehicle_Category',
        ),
    ]
