# Generated by Django 3.2.7 on 2023-01-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=20)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
