# Generated by Django 3.2.7 on 2023-01-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10)),
                ('floor_number', models.IntegerField()),
                ('number_of_spots', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
    ]
