# Generated by Django 3.2.7 on 2023-02-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20230130_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck')], max_length=20)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='parking_map',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='vacant', max_length=10),
        ),
    ]
