# Generated by Django 3.2.7 on 2023-02-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20230201_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck')], max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_hour_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('yearly_rate', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.DeleteModel(
            name='ParkingCharge',
        ),
    ]
