# Generated by Django 3.2.7 on 2023-02-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20230217_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parking_Spot',
            new_name='Generate_Spot',
        ),
    ]
