# Generated by Django 3.2.7 on 2023-02-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20230220_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generate_Spot',
        ),
        migrations.DeleteModel(
            name='Parking_Charge',
        ),
    ]
