# Generated by Django 3.2.7 on 2023-02-23 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0011_bookingrecord_generate_spot_parkingcharge_parkingsearch_vehicle_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('vehicle_number', models.CharField(max_length=255)),
                ('parking_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.parkingcharge')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.generate_spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.vehicle_category')),
            ],
        ),
        migrations.DeleteModel(
            name='BookingRecord',
        ),
    ]
