# Generated by Django 3.2.7 on 2023-02-24 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20230223_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('additional_hour_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('yearly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.vehicle_category', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking_record',
            name='parking_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.parking_charge'),
        ),
        migrations.DeleteModel(
            name='ParkingCharge',
        ),
    ]
